### ISSUE TITLE
Re convert an edited smash ultimate .eff doesnt work

### ISSUE THREAD

**Issue by schiggysmallz** [KillzXGaming/EffectLibrary#1]
i tried to edit an .eff file from smash ultimate which works perfectly fine in game.
but when i try to convert that edited .eff again i get this error
![image](https://github.com/KillzXGaming/EffectLibrary/assets/45839667/75839c08-26dd-473d-8e99-a6bf27e8994a)
also happens with fully unedited files.
how to reproduce
drag ef_mewtwo.eff (for example) into EffectConverter.exe
drag ef_mewtwo folder into EffectConverter.exe
drag ef_mewtwo_NEW.eff into EffectConverter.exe
produces error and doenst convert properly

**Comment by KillzXGaming** [comment]
Fixed as of https://github.com/KillzXGaming/EffectLibrary/commit/8524a4e05603d3377fac40e3515c424dc5d81f68
